name: Build and deploy Python project to Azure Function App - fitness-weekly-update

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  PYTHON_VERSION: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into Azure Functions package folder
        run: |
          python -m pip install --upgrade pip
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . \
            -x "venv/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "__pycache__/*" \
            -x "*.pyc"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FAD2871EB3284D96A8F3BD4D2AF85F95 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_05FFA30068B84A4F95FE53C91411C5EA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6CB9FA0809324D03852076D68664CE42 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: fitness-weekly-update
          slot-name: Production
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true